### ISSUE TITLE
InaccessibleObjectException Error On Coldfusion 2023

### ISSUE THREAD

**Issue by akelly777** [marcins/cf-google-authenticator#7]
When testing this code on Coldfusion 2023, I recieved this error:

<html>
<body>

ava.lang.reflect.InaccessibleObjectException: Unable to make public boolean com.sun.crypto.provider.PBKDF2KeyImpl.equals(java.lang.Object) accessible: module java.base does not "opens com.sun.crypto.provider" to unnamed module @21e45a6f
--
 
 
The error occurred in E:/Websites/AdminCopy23/Lib/cfc/Admin/Manage/authenticator/GoogleAuthenticator.cfc: line 140
138 :         var keySpec = createObject("java", "javax.crypto.spec.PBEKeySpec").init(arguments.password.toCharArray(), salt, 128, 80); 139 :         var secretKey = keyFactory.generateSecret(keySpec); 140 :         return Base32encode(secretKey.getEncoded()); 141 :     } 142 :

</body>
</html>

From what I've read here:

https://stackoverflow.com/questions/41265266/how-to-solve-inaccessibleobjectexception-unable-to-make-member-accessible-m

This could be caused by the introduction of  "[Java Platform Module System](http://openjdk.java.net/projects/jigsaw/spec/sotms) that was introduced in Java 9, particularly its implementation of strong encapsulation. It only allows [access](http://openjdk.java.net/projects/jigsaw/spec/sotms/#accessibility) under certain conditions, the most prominent ones are:

the type has to be public
the owning package has to be exported"

I'm puzzled in that this cfc works in CF 2018 which uses Java 10.

**Comment by carehart** [comment]
I don't have an answer for you (and am not involved in the project), but I have a couple of thoughts on this for you or the contributors. 

Beware first that CF2023 comes with Java 17 underlying it by default. That could introduce still more changes in this regard that may have arisin since the Java 10 you worked with in CF2018 (and while the very initial installer for it came with Java 10, months later and since then, the CF2018 installers come with Java 11--and will not likely ever come with Java 17, as support for CF2018 ends in July.) 

Second, be aware that your CF2023 install may have been modified by someone or something (including some migration process) which could have pulled in jvm arguments (in the jvm.config) whose values (including these --add-opens, --add-imports, and others) might NOT be the defaults which CF2023 would have come with. And THAT can lead to seemingly inexplcable oddities. Just something to consider.  If you KNOW that doesn't apply to you, ok.

**Comment by akelly777** [comment]
My absolute deepest thanks! I'll report back if I'm able to isolate a configuration issue that's causing this.

**Comment by akelly777** [comment]
Seems that even when largely mirroring the arguments from 2018 on Java 11, the problem persists. Thanks again for the suggestion! It could still help a pinpoint the issue closer to a difference between the interaction of Coldfusion with the code on Java 17 vs 11.

**Comment by akelly777** [comment]
I'm starting to wonder if the InaccessibleObjectException might be caused by the bytebuffer from buffer.array() that is being passed to mac.doFinal on line 90?

**Comment by akelly777** [comment]
This can be fixed with a configuration change:

--add-opens=java.base/com.sun.crypto.provider=ALL-UNNAMED

**Comment by carehart** [comment]
Thanks for sharing that.

**Comment by akelly777** [comment]
Cheers! Thanks for the suggestion.
